### ISSUE TITLE
Random algorithm is insufficent at providing optimal assignments

### ISSUE THREAD

**Issue by frereit** [johndoe31415/topicdist#1]
Currently the algorithm simply uses a few random tries and chooses the best fit. However, for larger sample sets, this clearly does not give optimal solutions. Since this repository almost exactly matches a classical assignment problem (except for a few modifications allowing for multiple matches), it is easily possible to validate that a much more optiomal solution exists using [scipy.optimizers.linear_sum_assignment](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html). Internally, this uses the hungarian method.

Here is a patch (requires the `scipy` package to be installed) that showcases the diference between the two methods (see below).

To use the hungarian method, we must construct a square cost matrix. First, 'clone' each topic by the amount of times it may be distributed. Secondly, add 'zero' students that do not have any preferences and can be assigned to the leftover topics. Note that this (trivially) does not change the problem statement and simply matches it to a square cost matrix.

```diff
diff --git a/topicdist b/topicdist
index 5b5f339..156bf7c 100755
--- a/topicdist
+++ b/topicdist
@@ -40,6 +40,34 @@ for run in range(args.attempt_count):
 	if (best_distribution is None) or (distribution.score > best_distribution.score):
 		best_distribution = distribution
 
-if args.verbose >= 1:
-	best_distribution.dump()
-best_distribution.write(args.output_file)
+print(f"Best score using randomness: {best_distribution.score}")
+
+from scipy.optimize import linear_sum_assignment
+
+topic_distributor = TopicDistributor(args)
+topics_headers = []
+student_headers = []
+cost_matrix = []
+
+for topic in topic_distributor._prefs.topics:
+	for _ in range(topic_distributor._max_assignments_for_topic(topic)):
+		topics_headers.append(topic)
+
+for student in topic_distributor._prefs.students:
+	student_headers.append(student)
+	row = []
+	for topic in topics_headers:
+		row.append(topic_distributor._prefs._students[student].prefs.get(topic, 0))
+	cost_matrix.append(row)
+
+# fill the remaining rows with zeros so we have a square matrix
+while len(cost_matrix) < len(cost_matrix[0]):
+	cost_matrix.append([0] * len(topics_headers))
+
+row_ind, col_ind = linear_sum_assignment(cost_matrix, maximize=True)
+score = 0
+for i, j in zip(row_ind, col_ind):
+	if i > len(student_headers) - 1:
+		break
+	score += cost_matrix[i][j]
+print(f'Best score using linear_sum_assignment: {score}')
```

To validate this, I have written a simple script to generate a larger test file (requires the `faker` package):

```python
import random
import faker

N_TOPICS = 25
N_STUDENTS = 60

f = faker.Faker()
topics = set()
while len(topics) < N_TOPICS:
    topics.add(" ".join(f.words()))

print('"Vollständiger Name",Gruppen,E-Mail-Adresse,Datum,' + ",".join(f'"{topic}"' for topic in topics))

names = set()
emails = set()
for student in range(N_STUDENTS):
    name = f.name()
    while name in names:
        name = f.name()
    email = f.email()
    while email in emails:
        email = f.email()
    names.add(name)
    emails.add(email)

    # random preferences
    prefs = list(range(N_TOPICS))
    random.shuffle(prefs)
    print(f'"{name}",,{email},,' + ",".join(str(pref) for pref in prefs))
```

Running `topicdist` with the random CSV shows a much better (actually optimal) result when using `linear_sum_assignment`

```bash
$ ./gen_random_testcase.py > rand.csv && ./topicdist rand.csv
Best score using randomness: 262
Best score using linear_sum_assignment: 1431
```

Here's the rand.csv file I used for this test: [rand.csv](https://github.com/johndoe31415/topicdist/files/13907300/rand.csv).

Perhaps it is worth to consider using the hungarian algorithm instead, either through a dependency like `scipy` or by pulling in an MIT single-file implementation like the [benchaplin/hungarian-algorithm](https://github.com/benchaplin/hungarian-algorithm/blob/master/hungarian_algorithm/algorithm.py)?

**Comment by johndoe31415** [comment]
Hey @frereit, thanks for the suggesion. I wasn't aware that scipy.optimize provided this functionality and it really seems quite straightforward to use. I've implemented this in c261e907. The advantage in a practical application ("Cyber Security Basics") does not seem to be so much different in terms of the total score in the current case of 23CS:

```
$ git rev-parse HEAD
26a0b5374cd130ec03434b66769c0dccca42f625
$ ./topicdist [...] -n 10000
Breakdown of preference matching:
   7 x 0
   2 x 1
   16 x 2
   43 x 3

Total students: 68
Total score: 163

$ git checkout main
$ git rev-parse HEAD
c261e9071237942f9963f6bde90f0f766f7fc8bf
$ ./topicdist [...]
Breakdown of preference matching:
   3 x 0
   6 x 1
   18 x 2
   41 x 3

Total students: 68
Total score: 165
```

But it does significantly improve the solution in the number of 0-assignments (we have only 2 students without any preference, which means only a single person got assigned a topic they did not choose). This is great!

Thanks for the input again. See you soon ;-) Cheers
